name: CI

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Tap syntax
        run: brew test-bot --only-tap-syntax
      - name: Cask audit
        run: brew audit --cask sunstatus
